package main

// This file is derived from xdaliclock 2.48 font D XBM files:
// https://www.jwz.org/xdaliclock/xdaliclock-2.48.tar.gz
//
// Original xdaliclock notice retained as required:
// xdaliclock - a melting digital clock
// Copyright © 1991-2022 Jamie Zawinski <jwz@jwz.org>
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation.  No representations are made about the suitability of this
// software for any purpose.  It is provided "as is" without express or
// implied warranty.
//
// Generated by reading font/{zero,one,two,three,four,five,six,seven,eight,nine,colon}D.xbm,
// scanning each row for filled [left,right) runs using XBM bit order, and
// retaining two segment slots per row. Blank rows use a zero-width segment
// at the glyph center; single-segment rows duplicate that segment, matching
// xdaliclock's number_to_frame replication rule. Each endpoint is encoded as
// one printable byte: values 0..63 are stored as byte(32+value), and values
// 64..90 as byte(33+value), avoiding backticks so the table can stay compact
// in raw string literals.

const maxSegments = 2

type segment struct {
	left  uint8
	right uint8
}

var fontD = [11]string{
	// 0: zeroD, 90x128
	`GRGRCVCVAYAY?[?[=]=];JP^:HQa9GSb8FTc6ETd5DUe5DUf4CVg3CVh2CWh1BWi0BWj0BWj/BXk.AXl.AXl-AXm-AXm,AXn,AXn+AYo+AYo*@Yp*@Yp*@Yq)@Yq)@Yq(@Yr(@Yr(@Yr(@Ys'@Ys'@Ys'@Ys&@Yt&@Yt&@Yt&@Yt&@Yu%@Yu%@Yu%@Yu%@Yu%@Yu%@Yv%@Yv$@Yv$@Yv$@Yv$@Yv$@Yv$@Yv$@Yv$@Yv$@Yv$@Yv$@Yv$@Yv$@Yv$@Yv$@Yv$@Yv$@Yv$@Yv$@Yv$@Yv$@Yv$@Yv$@Yv$@Yv%@Yv%@Yv%@Yu%@Yu%@Yu%@Yu%@Yu%@Yu%@Yu&@Yt&@Yt&@Yt&@Yt&@Yt'@Ys'@Ys'@Ys'@Ys(@Yr(@Yr(@Yr)@Yq)@Yq*@Yq*@Yp*AYp+AYo+AYo,AXn,AXn-AXm-AXm.AXl/AXl/BWk0BWk1BWj1BWi2CVh3CVh4CVg5DUf6DUe7ETd8FTc9FSb:HR_;IP^=]=]>[>[@Y@YCVCVGRGR`,
	// 1: oneD, 90x128
	`X\X\V\V\S\S\Q\Q\O\O\L\L\J\J\H\H\E\E\C\C\A\A\>\>\<\<\:\:\7\7\5\5\3\3\1\1\.\.\,\,\*7<\*3>\*0?\*-?\@\@\@\@\@\@\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\A\@]@]@]@]@]@]@]@]@]@]?^?^?^?^>_>_=_=_<a<a:c:c8e8e2j2j+q+q+q+q+q+q+q+q`,
	// 2: twoD, 90x128
	`GTGTCXCX@[@[>]>]<_<_:b:b9c9c7d7d6f6f5g5g4h4h3i3i2j2j1k1k0k0k/l/l/l/l.m.m-m-m-n-n,n,n+:Fo+7Io*5Ko*3Mo)2Np)1Op(0Pp(/Qp'.Rp'-Rp'-Sq&,Sq&+Tq%+Tq%*Uq%*Uq%)UqVpVpVpVpVpVpVpVpVpVpVpVpVoVoVoVoVoVoVnVnVnVnVnVnVmVmVmVmUlUlUlUlUkUkUkUkTjTjTjTjTiTiShShShShSgSgRfRfReReQdQdQdQdPcPcPbPbOaOaO_O_N^N^M]M]M\M\L[L[KZKZKYKYJXJXIWIWIVIVHUHUGTGTGSGSFRFREQEQDPDPCOCOCNCNBMBMALAL@Ktx?Isx>Hsx>Grw=Frw<Eqw;Dqw:Cpw9Bov8Aov8@nv7?mv6>ku5>hu4>]u3u3u2u2u1t1t1t1t0t0t/t/t.t.t-s-s,s,s+s+s*s*s)r)r(r(r'r'r'r'r&r&r%q%q$q$q#q#q"q"q"q"q"p"p"p"p"p"p`,
	// 3: threeD, 90x128
	`KVKVF[F[B^B^@a@a>c>c<e<e:f:f8g8g7h7h6i6i5j5j3k3k2l2l1m1m0>Dm/:Hn.8Kn.6Mn-4No,3Oo+2Po+1Qo*0Rp)/Rp).Sp(.Sp(-Sp',Tp),ToToToToToToToTnTnTnTnTnTnTmTmTmTmTlTlTlTlTkTkSjSjSiSiRhRhRgRgQfQfQdQdPcPcObObNbNbMdMdLfLfJhJhHiHiFjFjDlDlBmBm?n?n=o=o<p<p<p<p=q=q@r@rCrCrEsEsGsGsJtJtLtLtNtNtOuOuQuQuSuSuTvTvUvUvWvWvXvXvYvYvZwZwZwZw[w[w\w\w]w]w]w]w^w^w^w^w_w_w_v_vavavavavavavavavbvbvbububububububtbtbtbtbtbtbsbsbsbsbrbr,0br)4bq'6bq&8bp%9ap%;ao$<an$=am#?_m#@_l#A^k#B^j#C]i#D\h$E[g$FZe$HYd%IWc%KUa&_&_']']([([)Y)Y+W+W-T-T/Q/Q2M2M8G8G`,
	// 4: fourD, 90x128
	`]m]m\m\m[m[mZmZmZmZmYmYmXmXmWmWmVmVmVmVmUmUmTmTmSmSmSmSmRmRmQmQmPmPmPmPmOmOmNmNmMmMmMmMmLmLmKmKmJmJmImImImImHmHmGmGmFmFmFOQmENQmDNQmCMQmCLQmBKQmAKQm@JQm@IQm?HQm>HQm=GQm=FQm<FQm;EQm:DQm:CQm9CQm8BQm8AQm7@Qm6@Qm6?Qm5>Qm4>Qm3=Qm3<Qm2;Qm1;Qm1:Qm09Qm/8Qm/8Qm.7Qm-6Qm,6Qm,5Qm+4Qm*3Qm*3Qm)2Qm(1Qm'0Qm'0Qm&/Qm%.Qm%-Qm$-Qm#,Qm#+Qm"+Qm"x"x"x"x"x"x"x"x"x"x"x"x"x"x"x"x"x"x"x"x"x"x"x"x"x"x"x"x"x"x"x"x"x"x"x"x"x"xQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQm`,
	// 5: fiveD, 90x128
	`;x;x:w:w:w:w:w:w:v:v9v9v9v9v9u9u8u8u8u8u8t8t8t8t7t7t7s7s7s7s7s7s6r6r6r6r6r6r5q5q5q5q5q5q5p5p4;4;4;4;4:4:3:3:3:3:3:3:39392929292928281818181818181717070707070?0?0H0H/M/M/R/R/U/U.X.X.Z.Z.].]._._-a-a-c-c-e-e,f,f,g,g,h,h,i,i+j+j+k+k+l+l*m*m*n*n*n*n*o*o)p)p)p)p+q+q7q7q?q?qDrDrHrHrKsKsNsNsPsPsRsRsTtTtVtVtWtWtYtYtZtZt[t[t\t\t^t^t_t_t_t_tatatbtbtctctctctdtdtdtdtetetetetetetfsfsfsfsfsfsfsfsfrfrfrfrfrfrfqfq,1fq)5fp(7ep&9eo&;eo%<en$>dm$?dm$Acl$Bbk#Daj#E_i#G^h$I]g$K[f$MYe$QUd%b%b%a%a&^&^']']([([*Y*Y+W+W-T-T/Q/Q3M3M8F8F`,
	// 6: sixD, 90x128
	`pvpvjvjvevevavav\u\uYpYpWmWmTjTjRgRgOeOeMcMcLaLaJ^J^H]H]F[F[EZEZCYCYBWBWAVAV?U?U>T>T=S=S<R<R;Q;Q:Q:Q8P8P7O7O7N7N6N6N5M5M4L4L3L3L2K2K1J1J1J1J0I0I/I/I/H/H.H.H-H-H-G-G,G,G,F,F+F+F+F+F*E*E*E*E)E)E)D)D)DL\(DH_(c(c(e(e'g'g'h'h'j'j&k&k&DOl&CQm&BRn%BSo%BTp%AUq%AUq%AVr%AVr$AWs$AWs$AWt$AXt$@Xt$@Xu$@Xu$@Xu$@Yu$@Yu$@Yv$@Yv$@Yv$@Yv$@Yv$@Yv$@Yv$@Zv$@Zv$@Zv%@Zv%@Zv%@Zv%@Zv%@Zv%@Zv&@Zv&AZv&AZv&AZu'AZu'AZu'AZu(AZu(AZt(AZt)AZt)AZs*AZs*BZr+BZr+BZr,BZq,BYp-CYp.CYo/CYn/CYn0DYm1DXl2EXk3EXj4FWi6FVg7GUf8HTe:JRc<a<a>^>^@\@\CYCYHTHT`,
	// 7: sevenD, 90x128
	`*y*y*y*y)y)y)x)x)x)x)w)w)w)w(w(w(v(v(v(v(v(v(u(u'u'u'u'u't't't't't't&s&s&s&s&s&s&r&r&r&r%r%r%q%q%q%q%q%q%2_p$/_p$-_o$,^o$+^o$*^n$*]n#)]n#)]m#(\m#(\m#'\l"'[l"'[l"&Zk"&ZkZkZkYjYjYjYjYjYjXiXiXiXiWiWiWhWhWhWhVgVgVgVgVgVgUfUfUfUfUfUfTeTeTeTeSeSeSdSdSdSdRdRdRcRcRcRcQcQcQbQbQbQbPbPbPaPaOaOaOaOaO_O_N_N_N_N_N^N^M^M^M]M]L]L]L]L]L\L\K\K\K\K\K[K[J[J[J[J[JZJZIZIZIZIZHYHYHYHYHYHYGXGXGXGXGXGXFWFWFWFWFWFWEVEVEVEVDUDUDUDUDUDUCTCTCTCTCTCTBSBSBSBSASASARARARAR@R@R@Q@Q@Q@Q?Q?Q?P?P?P?P>P>P>O>O=O=O=O=O=N=N<N<N<M<M<M<M;M;M;L;L;L;L`,
	// 8: eightD, 90x128
	`GXGXB]B]>b>b;d;d9f9f7HRh6FTi4DVk3CWl1BXm0AYn/@Zo.@Zp-?[p,?[q,>[q+>\r*>\r*>\s)>]s)>]s(>]t(>]t(>]t'>]t'?]t'?]t'?]t'@]t'@]t&A]s&A]s&B]s'C]s'C]r'D]r'E\q'F\q'G\p'H[o(I[n(JZm(LZl)MYk)OYi*PXh*RWf+TVd+b+b,_,_-\-\.[.[.\.\/]/]0^0^1a1a2b2b3c3c5d5d6f6f7g7g8h8h:i:i;j;j=k=k>l>l>m>m>n>n;o;o8p8p6CEp4BGq2BHr1AJr/@Ks.@Ls-?Nt,?Ot+>Pt*>Ru)=Su)=Tu(<Uu(<Vv'<Vv';Wv&;Xv&;Yv&;Yv%;Zv%;Zv%:Zv%:[v%:[v%:[v%:\v%:\v%:\v%:\v%:\u%:\u%:\u%;\u%;\t%;\t&;\t&;\s&<\s'<\r'<[r'=[q(=[p)=[p)>Zo*>Zn+?Ym,@Xl-AWk.BVj/CUi1ETg3GQe4d4d6b6b9^9^;[;[?X?XDRDR`,
	// 9: nineD, 90x128
	`DRDR@V@V=Y=Y;\;\9^9^7GO_5EPb4DRc3CSd1BSf0BTg/ATh.AUi-@Uj-@Vj,@Vk+@Vl*?Vm*?Wm)?Wn)?Wn(?Wo(?Wp'?Xp'?Xq&>Xq&>Xq&>Xr&>Xr%>Xr%>Xs%>Xs%>Xs$>Xt$>Xt$>Xt$?Xt$?Yu$?Yu$?Yu$?Yu$?Yu$?Yu$?Yu$?Yu$?Yv$?Yv$?Yv$?Yv$@Yv$@Yv%@Yv%@Yv%@Yv%@Yv%AYv&AXv&AXv&AXv'BXu'BXu(BXu(CXu)CXu)DXu*DXu+EXt,FWt,GWt-HVt.JTt/s/s1s1s2s2s4s4s5r5r7r7r:QUq>MUqUqUqTpTpTpTpToToSoSoSoSoSnSnRmRmRmRmQlQlQlQlQkQkPjPjPjPjOiOiOhOhNhNhNgNgMfMfLeLeLdLdKcKcJbJbIaIaI_I_H^H^G]G]F\F\E[E[DYDYCXCXBWBWAUAU?T?T>R>R=Q=Q;O;O9M9M7K7K5I5I3G3G0E0E-C-C*@*@&=&=%:%:%6%6%1%1%*%*`,
	// 10: colonD, 46x128
	`777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777772;2;0>0>.?.?-@-@,B,B+B+B*C*C)D)D)D)D(E(E(E(E(E(E(F(F'F'F'F'F'F'F'F'F'F'F(F(F(E(E(E(E(E(E)D)D)D)D*C*C+B+B,A,A-@-@.?.?0=0=3:3:77777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777772;2;0>0>.?.?-A-A,B,B+B+B*C*C)D)D)D)D(E(E(E(E(E(E(F(F'F'F'F'F'F'F'F'F'F'F(F(F(E(E(E(E(E(E)D)D)D)D*C*C+B+B,A,A-@-@.?.?0=0=3:3:`,
}

func fontRow(glyph, row int) [maxSegments]segment {
	data := fontD[glyph]
	offset := row * maxSegments * 2
	return [maxSegments]segment{
		{decodeEndpoint(data[offset]), decodeEndpoint(data[offset+1])},
		{decodeEndpoint(data[offset+2]), decodeEndpoint(data[offset+3])},
	}
}

func decodeEndpoint(b byte) uint8 {
	if b < 97 {
		return b - 32
	}
	return b - 33
}
