//go:build ignore

// gen_teapot converts the original Utah teapot Bezier patches into the compact
// wire grid in teapot_mesh.go.
//
// Input: teapot_bezier from the University of Utah Model Repository,
// https://users.cs.utah.edu/~dejohnso/models/teapot_bezier
// ("original non-rational bezier teapot data ... from Martin Newell and Jim
// Blinn", transcribed by Thomas V Thompson II, 2000).
//
//	go run gen_teapot.go teapot_bezier > teapot_mesh.go
package main

import (
	"fmt"
	"math"
	"os"
	"regexp"
	"strconv"
)

const (
	steps = 5    // segments per patch edge
	scale = 2048 // model units -> int16 fixed point

	angleSteps = 1024
)

type vec [3]float64

func main() {
	src, err := os.ReadFile(os.Args[1])
	if err != nil {
		panic(err)
	}
	re := regexp.MustCompile(`pt\(\s*([-0-9.]+),\s*([-0-9.]+),\s*([-0-9.]+)\s*\)`)
	var pts []vec
	for _, m := range re.FindAllStringSubmatch(string(src), -1) {
		var p vec
		for i := range p {
			p[i], _ = strconv.ParseFloat(m[i+1], 64)
		}
		pts = append(pts, p)
	}
	if len(pts)%16 != 0 {
		panic("control points are not a multiple of 16")
	}
	patches := len(pts) / 16

	var lo, hi vec
	for i := range lo {
		lo[i], hi[i] = math.Inf(1), math.Inf(-1)
	}
	for _, p := range pts {
		for i := range p {
			lo[i], hi[i] = math.Min(lo[i], p[i]), math.Max(hi[i], p[i])
		}
	}
	var center vec
	for i := range center {
		center[i] = (lo[i] + hi[i]) / 2
	}

	type key [3]int16
	index := map[key]int{}
	var verts []key
	type edge [2]int
	seen := map[edge]bool{}
	var edges []edge
	vertex := func(p vec) int {
		var k key
		for i := range k {
			k[i] = int16(math.Round((p[i] - center[i]) * scale))
		}
		if i, ok := index[k]; ok {
			return i
		}
		index[k] = len(verts)
		verts = append(verts, k)
		return len(verts) - 1
	}
	addEdge := func(a, b int) {
		if a == b {
			return
		}
		if a > b {
			a, b = b, a
		}
		if !seen[edge{a, b}] {
			seen[edge{a, b}] = true
			edges = append(edges, edge{a, b})
		}
	}
	for p := 0; p < patches; p++ {
		var grid [steps + 1][steps + 1]int
		for i := 0; i <= steps; i++ {
			for j := 0; j <= steps; j++ {
				grid[i][j] = vertex(evalPatch(pts[p*16:p*16+16], float64(i)/steps, float64(j)/steps))
			}
		}
		for i := 0; i <= steps; i++ {
			for j := 0; j < steps; j++ {
				addEdge(grid[i][j], grid[i][j+1])
				addEdge(grid[j][i], grid[j+1][i])
			}
		}
	}

	fmt.Println("// Code generated by gen_teapot.go; DO NOT EDIT.")
	fmt.Println()
	fmt.Println("package main")
	fmt.Println()
	fmt.Printf("// %d Bezier patches, %dx%d segments each, centered, x%d fixed point, y up.\n", patches, steps, steps, scale)
	fmt.Printf("var teapotVerts = [%d][3]int16{\n", len(verts))
	for _, v := range verts {
		fmt.Printf("\t{%d, %d, %d},\n", v[0], v[1], v[2])
	}
	fmt.Println("}")
	fmt.Println()
	fmt.Printf("var teapotEdges = [%d][2]uint16{\n", len(edges))
	for _, e := range edges {
		fmt.Printf("\t{%d, %d},\n", e[0], e[1])
	}
	fmt.Println("}")
	fmt.Println()
	fmt.Println("// Q14 sine for one revolution.")
	fmt.Printf("var sinTable = [%d]int32{", angleSteps)
	for i := 0; i < angleSteps; i++ {
		if i%16 == 0 {
			fmt.Print("\n\t")
		} else {
			fmt.Print(" ")
		}
		fmt.Printf("%d,", q14(2*math.Pi*float64(i)/angleSteps))
	}
	fmt.Println("\n}")
}

func q14(rad float64) int32 { return int32(math.Round(math.Sin(rad) * (1 << 14))) }

func bernstein(t float64) [4]float64 {
	s := 1 - t
	return [4]float64{s * s * s, 3 * t * s * s, 3 * t * t * s, t * t * t}
}

func evalPatch(cp []vec, u, v float64) vec {
	bu, bv := bernstein(u), bernstein(v)
	var p vec
	for i := 0; i < 4; i++ {
		for j := 0; j < 4; j++ {
			w := bu[i] * bv[j]
			for k := range p {
				p[k] += w * cp[i*4+j][k]
			}
		}
	}
	return p
}
