//go:build rp2040 || rp2350

// Command picovgamandel draws the Mandelbrot set into a framebuffer displayed
// at 800x600 over VGA on the Pimoroni Pico VGA Demo Base.
//
// The display loop has no spare time in it. Video is generated by the CPU
// handing control words to a state machine and waiting on DMA, and it can never
// stop doing so, so there is nowhere in it to compute a fractal: stealing even
// a few dozen iterations per scanline starves the FIFO and the display loses
// sync.
//
// Both chips have two cores, so the render runs on the other one. The display
// loop keeps a core to itself and never yields, and the render has the second
// core to itself and may take as long as it likes. The picture paints itself in
// while the display runs, and the view zooms and redraws when it is finished.
//
// Both cores are required, so this must be built with the cores scheduler,
// which is not the default for these targets:
//
//	tinygo flash -target=pico -scheduler=cores ./rp2-pio/examples/picovgamandel/
//
// Built without it the render goroutine is never given a core to run on, since
// the display loop holds the only one and never yields, and the screen stays
// blank.
//
// The framebuffer is written by the render and read by DMA at the same time
// without any locking. The worst that does is show a half drawn picture, which
// is the point of drawing it progressively.
//
// Wiring is the Demo Base's own: nothing to connect beyond seating the board.
package main

import "github.com/tinygo-org/pio/rp2-pio/picovga"

const (
	// maxIter is the iteration limit. Raising it sharpens the set's edge and
	// lengthens the render in proportion.
	maxIter = 96
)

func main() {
	mode := picovga.Mode800x600RGB555
	mode.HScale, mode.VScale = scale, scale
	cfg := picovga.PimoroniVGA

	fb := &picovga.Framebuffer16{
		Pix:    pixels[:],
		Width:  mode.Width(),
		Height: mode.Height(),
	}
	fb.Fill(picovga.Black555)
	r := newRenderer(fb, maxIter)

	// The render has a core of its own, so it runs flat out alongside the
	// display without either waiting for the other.
	go render(r)

	sm, err := picovga.Setup(cfg, mode)
	if err != nil {
		panic(err)
	}
	dma := dmaChannelAt(0)
	ctrl := dma.ctrl(txDREQ(sm))
	txf := sm.TxReg()

	sync, back, out, front := mode.SyncWord(), mode.BackPorchWord(), mode.OutputWord(), mode.FrontPorchWord()
	blank := mode.BlankWords()

	put := func(w uint32) {
		for sm.IsTxFIFOFull() {
		}
		sm.TxPut(w)
	}

	sm.SetEnabled(true)
	for {
		for line := 0; line < mode.VTotal(); line++ {
			cfg.VSync.Set(mode.InVSync(line) == mode.PositiveVSync)
			row, visible := mode.VisibleLine(line)
			if !visible {
				put(sync)
				for _, w := range blank {
					put(w)
				}
				continue
			}
			put(sync)
			put(back)
			put(out)
			// The pixels must reach the FIFO after the output command and
			// before the front porch: all three go through the same FIFO and
			// their order is the line.
			dma.start(txf, fb.Line(row), ctrl)
			dma.wait()
			put(front)
		}
	}
}

// render draws the set over and over, zooming a little further in each time. It
// runs on the second core, so it is free to take as long as it needs and never
// pauses between pictures.
func render(r *renderer) {
	for {
		r.draw()
		r.zoom()
	}
}
